#!/bin/bash
# Circuit Breaker: Detects when Claude is going in circles
# Tracks edit frequency per file. Warns at 5x, blocks at 8x within 10 min.
# Dead-loop protection: BLOCK message explicitly forbids retry attempts.
INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')
[ -z "$FILE_PATH" ] && exit 0

# Whitelist: spec progress files and handoff docs are edited frequently by design
case "$FILE_PATH" in
  */specs/*.md|*/HANDOFF.md) exit 0 ;;
esac

PROJ_HASH=$(echo "$PWD" | shasum | cut -c1-8)
LOG="/tmp/claude-cb-${PROJ_HASH}.log"
touch "$LOG" && chmod 600 "$LOG" 2>/dev/null
NOW=$(date +%s)
WINDOW=600
WARN=5
BLOCK=8

# Raise thresholds when a spec is actively in-progress — planned edits, not a loop
if [ -d specs ] && grep -ql "Status.*in-progress" specs/*.md 2>/dev/null; then
  WARN=12
  BLOCK=20
  # Further raise when multiple specs are in-progress (spec-work-all batch scenario)
  SPEC_COUNT=$(grep -rl "Status.*in-progress" specs/*.md 2>/dev/null | wc -l | tr -d ' ')
  if [ "${SPEC_COUNT:-0}" -ge 2 ]; then
    WARN=25
    BLOCK=40
  fi
fi

echo "$NOW $FILE_PATH" >> "$LOG"

CUTOFF=$((NOW - WINDOW))
awk -v c="$CUTOFF" '$1 >= c' "$LOG" > "${LOG}.tmp" 2>/dev/null && mv "${LOG}.tmp" "$LOG"

COUNT=$(awk -v f="$FILE_PATH" 'NF>=2 && $2==f' "$LOG" 2>/dev/null | wc -l | tr -d ' ')

if [ "$COUNT" -ge "$BLOCK" ]; then
  echo "⛔ CIRCUIT BREAKER TRIGGERED — Edit blocked." >&2
  echo "" >&2
  echo "File    : ${FILE_PATH}" >&2
  echo "Edits   : ${COUNT}x in the last 10 minutes" >&2
  echo "" >&2

  # Show recent edit timestamps so Claude understands the pattern
  echo "Recent edit history (last 10):" >&2
  grep -F "$FILE_PATH" "$LOG" | tail -10 | while read -r ts _; do
    DELTA=$(( NOW - ts ))
    echo "  — ${DELTA}s ago" >&2
  done
  echo "" >&2

  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >&2
  echo "STOP. DO NOT attempt another edit to this file." >&2
  echo "DO NOT retry the same approach." >&2
  echo "DO NOT spawn a sub-agent that edits files." >&2
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >&2
  echo "" >&2
  echo "Required action:" >&2
  echo "  1. STOP all edit attempts immediately." >&2
  echo "  2. Summarize to the user: what were you trying to fix?" >&2
  echo "  3. Describe what approach you tried and why it failed." >&2
  echo "  4. Ask the user for a different strategy or guidance." >&2
  echo "" >&2
  echo "If you need to diagnose a build failure, you may spawn a" >&2
  echo "READ-ONLY Haiku sub-agent (no Write/Edit tools) to analyze" >&2
  echo "the error — but do NOT have it edit any files." >&2
  echo "" >&2
  echo "(Circuit breaker resets when the user sends the next message)" >&2
  exit 2
fi

if [ "$COUNT" -ge "$WARN" ]; then
  echo "⚠️  CIRCUIT BREAKER WARNING — Stop and reassess now." >&2
  echo "" >&2
  echo "File    : ${FILE_PATH}" >&2
  echo "Edits   : ${COUNT}x in the last 10 minutes (blocks at ${BLOCK})" >&2
  echo "" >&2
  echo "DO NOT edit this file again until a different approach is chosen." >&2
  echo "DO NOT retry the same fix on the same file." >&2
  echo "If diagnosis is needed, use a read-only Haiku agent first." >&2
fi

exit 0
