#!/bin/bash
# protect-and-breaker.sh — PreToolUse hook (Edit|Write)
# 1. Blocks edits to protected files (.env, lock files, build output)
# 2. Circuit breaker: detects edit loops, warns at threshold, blocks at limit

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')
[ -z "$FILE_PATH" ] && exit 0

# --- Protected file check ---
PROTECTED=(".env" "package-lock.json" "pnpm-lock.yaml" "yarn.lock" "bun.lockb" "composer.lock" ".git/")

for pattern in "${PROTECTED[@]}"; do
  if [[ "$FILE_PATH" == *"$pattern"* ]]; then
    echo "Blocked: $FILE_PATH is protected ('$pattern')" >&2
    exit 2
  fi
done

if [[ "$FILE_PATH" == */assets/* ]]; then
  for cfg in vite.config.js vite.config.ts vite.config.mjs vite.config.mts; do
    if [ -f "$cfg" ]; then
      echo "Blocked: $FILE_PATH is in assets/ (build output — edit src/ instead)" >&2
      exit 2
    fi
  done
fi

# --- Circuit breaker ---
# Spec files and handoff docs are edited frequently by design
case "$FILE_PATH" in
  */specs/*.md|*/.continue-here.md|*/HANDOFF.md) exit 0 ;;
esac

PROJECT_ROOT="${CLAUDE_PROJECT_DIR:-$PWD}"
PROJ_HASH=$(echo "$PROJECT_ROOT" | shasum | cut -c1-8)
LOG="/tmp/claude-cb-${PROJ_HASH}.log"
touch "$LOG" && chmod 600 "$LOG" 2>/dev/null
NOW=$(date +%s)
WINDOW=600
WARN=5
BLOCK=8

# Raise thresholds when specs are actively in-progress
if [ -d specs ] && grep -ql "Status.*in-progress" specs/*.md 2>/dev/null; then
  WARN=12
  BLOCK=20
  SPEC_COUNT=$(grep -rl "Status.*in-progress" specs/*.md 2>/dev/null | wc -l | tr -d ' ')
  if [ "${SPEC_COUNT:-0}" -ge 2 ]; then
    WARN=25
    BLOCK=40
  fi
fi

# Tab delimiter to handle spaces in file paths
printf '%s\t%s\n' "$NOW" "$FILE_PATH" >> "$LOG"

CUTOFF=$((NOW - WINDOW))
awk -F'\t' -v c="$CUTOFF" '$1 >= c' "$LOG" > "${LOG}.tmp" 2>/dev/null && mv "${LOG}.tmp" "$LOG"

COUNT=$(awk -F'\t' -v f="$FILE_PATH" '$2==f' "$LOG" 2>/dev/null | wc -l | tr -d ' ')

if [ "$COUNT" -ge "$BLOCK" ]; then
  echo "CIRCUIT BREAKER TRIGGERED — Edit blocked." >&2
  echo "" >&2
  echo "File    : ${FILE_PATH}" >&2
  echo "Edits   : ${COUNT}x in the last 10 minutes" >&2
  echo "" >&2
  grep -F "$FILE_PATH" "$LOG" | tail -10 | while read -r ts _; do
    DELTA=$(( NOW - ts ))
    echo "  - ${DELTA}s ago" >&2
  done
  echo "" >&2
  echo "STOP. DO NOT attempt another edit to this file." >&2
  echo "DO NOT retry the same approach." >&2
  echo "DO NOT spawn a sub-agent that edits files." >&2
  echo "" >&2
  echo "Required action:" >&2
  echo "  1. STOP all edit attempts immediately." >&2
  echo "  2. Summarize to the user: what were you trying to fix?" >&2
  echo "  3. Describe what approach you tried and why it failed." >&2
  echo "  4. Ask the user for a different strategy or guidance." >&2
  echo "" >&2
  echo "(Circuit breaker resets when the user sends the next message)" >&2
  exit 2
fi

if [ "$COUNT" -ge "$WARN" ]; then
  echo "WARNING — Circuit breaker approaching limit." >&2
  echo "" >&2
  echo "File    : ${FILE_PATH}" >&2
  echo "Edits   : ${COUNT}x in the last 10 minutes (blocks at ${BLOCK})" >&2
  echo "" >&2
  echo "DO NOT edit this file again until a different approach is chosen." >&2
  echo "If diagnosis is needed, use a read-only Haiku agent first." >&2
fi

exit 0
