#!/bin/bash
# build-summary.sh — Generates .agents/context/SUMMARY.md
# Called by /context-refresh after regenerating context files.
# Sources: STACK.md > ARCHITECTURE.md > AUDIT.md > CONCEPT.md > any other *.md
#          in .agents/context/ with YAML frontmatter abstract:.
# Any domain-specific context file (STORYBLOK.md, SHOPIFY.md, etc.) with
# frontmatter `abstract:` is auto-included alphabetically after the standard set.
# Output: max 50 lines, marker <!-- GENERATED --> at top.

set -e

CONTEXT_DIR="${CLAUDE_PROJECT_DIR:-.}/.agents/context"
OUTPUT="$CONTEXT_DIR/SUMMARY.md"
GRAPH_FILE="$CONTEXT_DIR/graph.json"

# --- Helpers ---

# Extract YAML frontmatter value by key from a file
# Usage: extract_frontmatter_key <file> <key>
extract_frontmatter_key() {
  local file="$1"
  local key="$2"
  local in_frontmatter=0
  local line_num=0

  [ -f "$file" ] || return 0

  while IFS= read -r line; do
    line_num=$((line_num + 1))
    if [ "$line_num" -eq 1 ]; then
      [ "$line" = "---" ] && in_frontmatter=1 || return 0
      continue
    fi
    [ "$in_frontmatter" -eq 0 ] && return 0
    [ "$line" = "---" ] && return 0
    case "$line" in
      "${key}:"*)
        val="${line#${key}:}"
        val="${val# }" # strip single leading space (standard YAML)
        val="${val#\"}"
        val="${val%\"}"
        echo "$val"
        return 0
        ;;
    esac
  done < "$file"
}

# Extract YAML sections list (up to N items) from frontmatter
# Usage: extract_sections <file> <max_count>
extract_sections() {
  local file="$1"
  local max="$2"
  local in_frontmatter=0
  local in_sections=0
  local count=0
  local line_num=0

  [ -f "$file" ] || return 0

  while IFS= read -r line; do
    line_num=$((line_num + 1))
    if [ "$line_num" -eq 1 ]; then
      [ "$line" = "---" ] && in_frontmatter=1 || return 0
      continue
    fi
    [ "$in_frontmatter" -eq 0 ] && return 0
    [ "$line" = "---" ] && return 0
    case "$line" in
      sections:)
        in_sections=1
        ;;
      "  - "*)
        if [ "$in_sections" -eq 1 ] && [ "$count" -lt "$max" ]; then
          entry="${line#  - }"
          entry="${entry#\"}"
          entry="${entry%\"}"
          echo "  - $entry"
          count=$((count + 1))
        fi
        ;;
      *)
        in_sections=0
        ;;
    esac
  done < "$file"
}

# --- Build SUMMARY ---

{
  echo "<!-- GENERATED by build-summary.sh — do not edit manually. Run /context-refresh to update. -->"
  echo ""
  echo "# Project Summary"
  echo ""

  # Emit a context file: heading = filename (minus .md, title-cased),
  # body = frontmatter abstract + up to N sections. Returns 0 if emitted.
  emit_context_file() {
    local file="$1"
    local max_sections="$2"
    local heading="$3"
    [ -f "$file" ] || return 1
    local abstract
    abstract=$(extract_frontmatter_key "$file" "abstract")
    [ -n "$abstract" ] || return 1
    echo "## $heading"
    echo "$abstract"
    [ "$max_sections" -gt 0 ] && extract_sections "$file" "$max_sections"
    echo ""
  }

  # Standard set in priority order
  emit_context_file "$CONTEXT_DIR/STACK.md" 3 "Stack" || true
  emit_context_file "$CONTEXT_DIR/ARCHITECTURE.md" 3 "Architecture" || true
  emit_context_file "$CONTEXT_DIR/AUDIT.md" 5 "Audit" || true
  emit_context_file "$CONTEXT_DIR/CONCEPT.md" 0 "Concept" || true

  # Auto-discover: any other *.md in context/ with frontmatter abstract:
  # (STORYBLOK.md, SHOPIFY.md, WORDPRESS.md, custom domain context, etc.)
  if [ -d "$CONTEXT_DIR" ]; then
    for file in "$CONTEXT_DIR"/*.md; do
      [ -f "$file" ] || continue
      base=$(basename "$file" .md)
      case "$base" in
        STACK | ARCHITECTURE | AUDIT | CONCEPT | SUMMARY | PATTERNS | CONVENTIONS) continue ;;
      esac
      # Title-case heading: STORYBLOK -> Storyblok
      heading=$(echo "$base" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')
      emit_context_file "$file" 2 "$heading" || true
    done
  fi

  # GRAPH: top hub files (most-imported — navigation context)
  if [ -f "$GRAPH_FILE" ] && command -v jq > /dev/null 2>&1; then
    hub_count=$(jq -r '.stats.top_hubs | length' "$GRAPH_FILE" 2> /dev/null || echo "0")
    if [ "$hub_count" -gt 0 ]; then
      echo "## Top Hubs"
      jq -r '.stats.top_hubs[] | "  - \(.file) (\(.imported_by)x imports)"' "$GRAPH_FILE" 2> /dev/null | head -5
      echo ""
    fi
  fi

} > "$OUTPUT"

# Enforce 50-line limit: truncate if over and append a marker
line_count=$(wc -l < "$OUTPUT")
if [ "$line_count" -gt 50 ]; then
  tmp=$(mktemp)
  trap 'rm -f "$tmp"' EXIT
  head -50 "$OUTPUT" > "$tmp"
  echo "<!-- truncated at 50 lines -->" >> "$tmp"
  mv "$tmp" "$OUTPUT"
  trap - EXIT
fi

echo "SUMMARY.md generated: $(wc -l < "$OUTPUT") lines → $OUTPUT"
