#!/bin/bash
# build-summary.sh — Generates .agents/context/SUMMARY.md
# Called by /context-refresh after regenerating context files.
# Sources: AUDIT.md + ARCHITECTURE.md frontmatter + CONCEPT.md (if present) + graph.json top_hubs
# Output: max 50 lines, marker <!-- GENERATED --> at top.

set -e

CONTEXT_DIR="${CLAUDE_PROJECT_DIR:-.}/.agents/context"
OUTPUT="$CONTEXT_DIR/SUMMARY.md"
GRAPH_FILE="$CONTEXT_DIR/graph.json"

# --- Helpers ---

# Extract YAML frontmatter value by key from a file
# Usage: extract_frontmatter_key <file> <key>
extract_frontmatter_key() {
  local file="$1"
  local key="$2"
  local in_frontmatter=0
  local line_num=0

  [ -f "$file" ] || return 0

  while IFS= read -r line; do
    line_num=$((line_num + 1))
    if [ "$line_num" -eq 1 ]; then
      [ "$line" = "---" ] && in_frontmatter=1 || return 0
      continue
    fi
    [ "$in_frontmatter" -eq 0 ] && return 0
    [ "$line" = "---" ] && return 0
    case "$line" in
      "${key}:"*)
        val="${line#${key}:}"
        val="${val# }"   # strip single leading space (standard YAML)
        val="${val#\"}"
        val="${val%\"}"
        echo "$val"
        return 0
        ;;
    esac
  done < "$file"
}

# Extract YAML sections list (up to N items) from frontmatter
# Usage: extract_sections <file> <max_count>
extract_sections() {
  local file="$1"
  local max="$2"
  local in_frontmatter=0
  local in_sections=0
  local count=0
  local line_num=0

  [ -f "$file" ] || return 0

  while IFS= read -r line; do
    line_num=$((line_num + 1))
    if [ "$line_num" -eq 1 ]; then
      [ "$line" = "---" ] && in_frontmatter=1 || return 0
      continue
    fi
    [ "$in_frontmatter" -eq 0 ] && return 0
    [ "$line" = "---" ] && return 0
    case "$line" in
      sections:)
        in_sections=1
        ;;
      "  - "*)
        if [ "$in_sections" -eq 1 ] && [ "$count" -lt "$max" ]; then
          entry="${line#  - }"
          entry="${entry#\"}"
          entry="${entry%\"}"
          echo "  - $entry"
          count=$((count + 1))
        fi
        ;;
      *)
        in_sections=0
        ;;
    esac
  done < "$file"
}

# --- Build SUMMARY ---

{
  echo "<!-- GENERATED by build-summary.sh — do not edit manually. Run /context-refresh to update. -->"
  echo ""
  echo "# Project Summary"
  echo ""

  # AUDIT: abstract + all sections (Critical/High findings are in sections)
  AUDIT_FILE="$CONTEXT_DIR/AUDIT.md"
  if [ -f "$AUDIT_FILE" ]; then
    audit_abstract=$(extract_frontmatter_key "$AUDIT_FILE" "abstract")
    if [ -n "$audit_abstract" ]; then
      echo "## Audit"
      echo "$audit_abstract"
      extract_sections "$AUDIT_FILE" 5
      echo ""
    fi
  fi

  # ARCHITECTURE: abstract + key sections
  ARCH_FILE="$CONTEXT_DIR/ARCHITECTURE.md"
  if [ -f "$ARCH_FILE" ]; then
    arch_abstract=$(extract_frontmatter_key "$ARCH_FILE" "abstract")
    if [ -n "$arch_abstract" ]; then
      echo "## Architecture"
      echo "$arch_abstract"
      extract_sections "$ARCH_FILE" 3
      echo ""
    fi
  fi

  # CONCEPT: abstract (if present — project-specific principles)
  CONCEPT_FILE="$CONTEXT_DIR/CONCEPT.md"
  if [ -f "$CONCEPT_FILE" ]; then
    concept_abstract=$(extract_frontmatter_key "$CONCEPT_FILE" "abstract")
    if [ -n "$concept_abstract" ]; then
      echo "## Concept"
      echo "$concept_abstract"
      echo ""
    fi
  fi

  # GRAPH: top hub files (most-imported — navigation context)
  if [ -f "$GRAPH_FILE" ] && command -v jq >/dev/null 2>&1; then
    hub_count=$(jq -r '.stats.top_hubs | length' "$GRAPH_FILE" 2>/dev/null || echo "0")
    if [ "$hub_count" -gt 0 ]; then
      echo "## Top Hubs"
      jq -r '.stats.top_hubs[] | "  - \(.file) (\(.imported_by)x imports)"' "$GRAPH_FILE" 2>/dev/null | head -5
      echo ""
    fi
  fi

} > "$OUTPUT"

# Enforce 50-line limit: truncate if over and append a marker
line_count=$(wc -l < "$OUTPUT")
if [ "$line_count" -gt 50 ]; then
  tmp=$(mktemp)
  trap 'rm -f "$tmp"' EXIT
  head -50 "$OUTPUT" > "$tmp"
  echo "<!-- truncated at 50 lines -->" >> "$tmp"
  mv "$tmp" "$OUTPUT"
  trap - EXIT
fi

echo "SUMMARY.md generated: $(wc -l < "$OUTPUT") lines → $OUTPUT"
